#!/bin/sh

# Wrapper on p4 that displays any command
p4()
{
    echo "> p4 $*" >&2
    env p4 "$@"
}

p4x_get_user()
{
    p4 user -o | grep -v '^#' | grep 'User:' | cut -d"	" -f2
}

p4x_usage()
{
    if [ $# -lt 2 ]; then
        echo "p4x_usage requires at least 2 arguments: n_args and usage" >&2
        exit 1
    fi
    n_args="$1"
    usage="$2"
    shift
    shift

    if [ $# -ne $n_args ]; then
        echo "Usage: $0 $cmd $usage" >&2
        exit 0
    fi
}

# Quit on error
set -e

if [ $# -le 0 ]; then
    cat >&2 << EOF
Usage: $0 <command> [args...]

Commands:
changes [args...]: runs p4 changes -u <p4-user> [args...]
diff [args...]: runs p4 diff -du [args...] | colordiff
diffcl <cl-number>: runs p4 diff -du \$(p4 opened -c <cl-number> | cut -d# -f1) | colordiff
pending [args...]: runs p4 changes -u <p4-user> -s pending [args...]
reshelve <cl-number>: runs p4 shelve -dc <cl-number> && p4 shelve -c <cl-number>
shelved [args...]: runs p4 changes -u <p4-user> -s shelved [args...]
submit <cl-number>: runs p4 shelve -dc <cl-number> && p4 submit -c <cl-number>
submitted [args...]: runs p4 changes -u <p4-user> -s submitted [args...]
EOF
    exit 0
fi

cmd="$1"
shift

case "$cmd" in
    "changes")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER $*
        ;;
    "diff")
        p4 diff -du $* | colordiff
        ;;
    "diffcl")
        p4x_usage 1 "<cl-number>" "$@"
        IFS='
'
        if [ "$(env p4 opened -c $1 2>&1)" = "File(s) not opened on this client." ]; then
            echo "No opened file for the specified changelist on this client." >&2
            exit 1
        fi
        p4 diff -du $(p4 opened -c $1 | cut -d# -f1) | colordiff
        ;;
    "pending")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER -s pending $*
        ;;
    "reshelve")
        p4x_usage 1 "<cl-number>" "$@"
        p4 shelve -dc $1 && p4 shelve -c $1
        ;;
    "shelved")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER -s shelved $*
        ;;
    "submit")
        p4x_usage 1 "<cl-number>" "$@"
        p4 shelve -dc $1 && p4 submit -c $1
        ;;
    "submitted")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER -s submitted $*
        ;;
    *)
        echo "$0: $cmd: unknown command" >&2
        ;;
esac
