#!/bin/sh

p4()
{
    echo "> p4 $*" >&2
    env p4 "$@"
}

p4x_get_user()
{
    p4 user -o | grep -v '^#' | grep 'User:' | cut -d"	" -f2
}

# Quit on error
set -e

if [ $# -le 0 ]; then
    cat >&2 << EOF
Usage: $0 <command> [args...]

Commands:
changes [args...]: runs p4 changes -u <p4-user> [args...]
diff [args...]: runs p4 diff -du [args...] | colordiff
diffcl <cl-number>: runs p4 diff -du \$(p4 opened -c <cl-number> | cut -d# -f1) | colordiff
pending [args...]: runs p4 changes -u <p4-user> -s pending [args...]
reshelve <cl-number>: runs p4 shelve -dc <cl-number> && p4 shelve -c <cl-number>
shelved [args...]: runs p4 changes -u <p4-user> -s shelved [args...]
EOF
    exit 0
fi

cmd="$1"
shift

case "$cmd" in
    "changes")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER $*
        ;;
    "diff")
        p4 diff -du $* | colordiff
        ;;
    "diffcl")
        if [ $# -ne 1 ]; then
            cat >&2 << EOF
Usage: $0 $cmd <cl-number>
EOF
            exit 0
        fi
        IFS='
'
        p4 diff -du $(p4 opened -c $1 | cut -d# -f1) | colordiff
        ;;
    "pending")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER -s pending $*
        ;;
    "reshelve")
        if [ $# -ne 1 ]; then
            cat >&2 << EOF
Usage: $0 $cmd <cl-number>
EOF
            exit 0
        fi
        p4 shelve -dc $1 && p4 shelve -c $1
        ;;
    "shelved")
        P4USER="$(p4x_get_user)"
        p4 changes -u $P4USER -s shelved $*
        ;;
    *)
        echo "$0: $cmd: unknown command" >&2
        ;;
esac
